### ISSUE TITLE
Company name strings in translation file

### ISSUE THREAD

**Issue by goranvrbaski** [mint-hosting/whmcs-serbian-translation#3]
**Is your feature request related to a problem? Please describe.**
Yes, when we use this translation we see company-specific translations. For example: 

```php
$_LANG['clientareatitle'] = "Moj Mint korisnički servis";
...

```

**Describe the solution you'd like**
There shouldn't be company-specific strings in the translation file so everyone can use it without any modifications.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by igorhrcek** [comment]
Yeah, we've missed that one :/ issue is resolved!

**Comment by goranvrbaski** [comment]
> Yeah, we've missed that one :/ issue is resolved!

Wow, that was quick. Thanks! 😄
